package com.jami.utilities.guildOptions;

public enum OptionType {
  EXP_INCREMENT,
  EXP_VARIATION,
  EXP_COOLDOWN,
  LEVEL_BASE,
  LEVEL_GROWTH,
  LOGGING_CHANNEL_ADD,
  LOGGING_CHANNEL_REMOVE,
  LEVELLING_ROLE_ADD,
  LEVELLING_ROLE_REMOVE,
  DISABLED_FEATURE_ADD,
  DISABLED_FEATURE_REMOVE,
  WORDS_DISABLED_CHANNEL_ADD,
  WORDS_DISABLED_CHANNEL_REMOVE
}
